export type EmployeeFormValues = {
  name: string;
  active: boolean;
  nationalId: string;
  address: string;
  phone: string;
  mobile: string;
  email: string;
  genderId: number | undefined;
  branchId: number | undefined;
  socialId: string;
  maritalStatusId: number | null;
  militaryStatusId: number | undefined;
  birthDate: string;
  countryId: number | null;
  stateId: number | null;
  cityId: number | null;
  notes: string;
  jobId: number | undefined;
};
